spring:
  application:
    name: admin-client
server:
  port: 12005
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    #是否需要注册到注册中心，因为该项目本身作为服务注册中心
    register-with-eureka: true
    #是否需要从注册中心获取服务列表
    fetch-registry: true
  instance:
    metadata-map:
      management:
        context-path: ${management.context-path}
    health-check-url-path: ${management.context-path}/health
management:
  context-path: /manage
  security:
    enabled: false
security:
  user:
    name: client
    password: client
  basic:
    enabled: true
    path: /manage