spring:
  application:
    name: spring-boot-with-activiti
  datasource:
    url: jdbc:h2:mem:test
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console
  activiti:
    history-level: full #full will record all infomation of process
