spring:
  application:
    name: admin
  jackson:
    serialization:
      indent-output: true
endpoints:
  health:
    sensitive: true
    enabled: true
server:
  port: 12000
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    #是否需要注册到注册中心，因为该项目本身作为服务注册中心
    register-with-eureka: true
    #是否需要从注册中心获取服务列表
    fetch-registry: true
    registry-fetch-interval-seconds: 5
  instance:
    metadata-map:
      management:
        context-path: ${management.context-path}
      user:
        name: client
        password: client
    health-check-url-path: ${management.context-path}/health
management:
  security:
    enabled: false
  context-path: /manage
security:
  user:
    name: client
    password: client
  basic:
    enabled: true