spring:
  cloud:
    config:
      allowOverride: true
      overrideNone: true
      overrideSystemProperties: false

charles:
  didispace:
    dev:
      value: didispace-dev.yml
common:
  base:
    value: didispace-dev.yml