spring:
  cloud:
    config:
      allowOverride: true
      overrideNone: true
      overrideSystemProperties: false
charles:
  didispace:
    value: didispace.yml
common:
  base:
    value: didispace.yml