spring:
  application:
    name: aop
  aop:
    #auto: true # or you can add @EnableAspectJAutoProxy.
    proxy-target-class: false # Whether subclass-based (CGLIB) proxies are to be created (true) as opposed to standard Java interface-based proxies (false).
server:
  port: 8105
